services:
  - type: web
    name: jazzcash-easypaisa-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
